# Copy / Paste
bind = SUPER, C, exec, wl-copy
bind = SUPER, V, exec, omarchy-clipboard-paste
bind = SUPER, X, exec, omarchy-clipboard-cut
bind = SUPER CTRL, V, exec, omarchy-launch-walker -m clipboard
